### ISSUE TITLE
renderBlock function needs to renamed in Sulu 2.5.11 & Symfony 6.4

### ISSUE THREAD

**Issue by TheCadien** [alengodev/alengoFormBundle#12]
See [Upgrade.md ](https://github.com/sulu/sulu/blob/2.5/UPGRADE.md#rename-websitecontrollerrenderblock-to-websitecontrollerrenderblockview)

They are found in the [FormDataController](https://github.com/alengodev/alengoFormBundle/blob/master/Controller/FormDataController.php#L37)

**Comment by alengodev** [comment]
Fixed in [v1.4.2](https://github.com/alengodev/alengoFormBundle/releases/tag/1.4.2)
